version: '3'

services:

  app:
    container_name: my_bot
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    command: "npm run serve"
    env_file:
      - .env
    volumes:
        - ./database:/app/database
        - ./logs/:/app/logs
    restart: always