name: Build

on:
  # push:
  #   branches: [ main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allow the workflow to be re-used in other workflows
  workflow_call:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/workflows/build
      - uses: actions/setup-node@v3
        with:
          node-version: 17.6.0
          cache: 'npm'
      - run: npm ci
      - run: npm run build